version: 0.0
os: linux
files:
  - source: /dist
    destination: /home/ec2-user/myapp

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 300
